<?php

$caminho = dirname(__DIR__);

require_once $caminho . '/app/includes/config.php';
$config['urlSistema'] = 'http://' . $config['url'];

require_once $caminho . '/app/includes/funcoes.php';
require_once $caminho . '/detran/includes/funcoes.php';
require_once $caminho . '/app/classes/PHPMailer/PHPMailerAutoload.php';
require_once $caminho . '/app/classes/core.class.php';
require_once $caminho . '/app/classes/orio/Transacoes.php';
require_once $caminho . '/app/includes/config.interfaces.php';
require_once $caminho . '/app/classes/detran.class.php';
$detran = new Detran();
$estadosDetran = $detran->listarEstadosIntegrados();

$coreObj = new Core;
$transacoes = new Transacoes();


/**
 * Passos para envio de créditos DETRAN-SE
 *
 * 1- Alterar as strings informadas pelo cliente adicionando o espaçamento aceito pelo detran(usar exemplo das strings abaixo).
 *
 * 2 - Alterar matrícula para a informada pelo cliente.
 *
 * 3 - Adicionar arquivo via ftp na pasta /detran no servidor do cliente (Icetran ou Ibreptran)
 *
 * 4 - Criar uma nova cron no plesk e adicionar esse arquivo
 *
 * 5 - E executar (não precisa salvar)
 *
 * 6 - Verificar no banco do cliente na tabela detran_logs se as strings foram enviadas e tiveram retorno de sucesso (filtrar por idmatricula e ordenar por data_cad)
 *
 * 7 - Informar no card se todos os envios tiveram sucesso, caso não informar qual string retornou erro.
 * string: idcfc,cfc,cpf instrutor, cpf aluno,data da aula,horario inicio da aula, horario fim,disciplina,porcentagem biometria
 */

$strings = array(
    
    '424cfc16603477780053027801185392023032412001250 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032413001350 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032414001450 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032415001550 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032417001750 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032418001850 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032419001950 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032420002050 DR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032506000650 SR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032507000750 SR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032508000850 SR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032509000950 SR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032511001150 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032512001250 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032513001350 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032514001450 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032606000650 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032607000750 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032608000850 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032609000950 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032611001150 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032612001250 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032613001350 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032614001450 LR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032706000650 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032707000750 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032708000850 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032709000950 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032711001150 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    '424cfc16603477780053027801185392023032712001250 RR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     09000',
    
);

$matricula = 91045;

foreach ($strings as $stringEnvio) {

    $detran->CreditosEspecificoSE($stringEnvio, $matricula);

}
